Fix: JaCoCo exclude patterns format
Fix JaCoCo exclude patterns format. JJB 6.x does not process
the job config when double quotes are used and returns the
following error.

Error:
requests.exceptions.HTTPError: 500 Server Error: Server Error for url:
https://jenkins.opendaylight.org/releng/job/distribution-\
merge-managed-argon/config.xml

Signed-off-by: Anil Belur <abelur@linuxfoundation.org>
Change-Id: I6c32d6d9e510a026af59f3dce0ca6a5fc6847dce