fix: Add local_build variable to packer templates
Add the local_build variable to robot, helm, and mininet-ovs-217
templates to match common-packer templates structure.

This variable is required by packer-build-action when building via
SSH bastion. Without it, packer fails with:

  Error: Undefined -var variable
  A "local_build" variable was passed in the command line but was
  not found in known variables.

The variable was already present in common-packer templates
(builder, docker) but missing from ODL-specific templates.

Templates updated:
- packer/templates/robot.pkr.hcl
- packer/templates/helm.pkr.hcl
- packer/templates/mininet-ovs-217.pkr.hcl

Change-Id: If980cd7287a40816b57929a63e1cdd33a6c469de
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>