python2 is EOL
tox veriy fails with
ImportError: No module named zipp
which no longer supports python2

Signed-off-by: Aric Gardner <agardner@linuxfoundation.org>
Change-Id: I66bc2582376932db446d12806b2f0d58c211a934