Update patch set 1
Patch Set 1:

> > And I was unable to "integrate" new default values in a new file
 > (i
 > > failed command jenkins-jobs --conf ../../jenkins.ini test . ), so
 > i
 > > put default plot values to releng-defaults
 > 
 > Do you have an example of what you tried so I can see why it may
 > have failed?
 > 
 > I think unless these defaults applies globally to all projects, we
 > shouldn't keep it in releng-defaults.

it happened when i created integration-defautls.yaml (instead of modifying remeng-defaults)
- defaults:
    name: plot-defaults

    plot-title: ''
    plot-yaxis: ''
    plot-group: 'Default Plot Group'
    plot-data-file: 'plot-data.csv'

and when i worked with "noplot" job (so i was not going to override these variables)
....
   deep_format(obj[item], paramdict)
  File "/home/cisco/virtenvs/default/local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 97, in deep_format
    raise JenkinsJobsException(desc)
jenkins_jobs.errors.JenkinsJobsException: plot-title parameter missing to format {plot-title}
Given:

Patch-set: 1