Install openldap-dev package for CentOS and Ubuntu
ldap ber headers are required while installing lftools
for releng/lftools change #4054. Fixes the below error:

Modules/errors.h:8:18: fatal error: lber.h: No such file or directory

Change-Id: Icbbdaca341673fd1b65710b362a63c0b9f56feb6
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>