Update patch set 2
Patch Set 2:

> ok, next error with this latest ps is:
 > 
 > TypeError: cannot serialize 1 (type int)

See my email on int-dev. You need to install the latest JJB 2.9.1

https://lists.opendaylight.org/pipermail/integration-dev/2018-December/012760.html

Patch-set: 2