Update patch set 1
Patch Set 1:

Srinivas, I've issued a recheck on the CR, if it does not go thru please open a ticket with helpdesk so that someone can look into the tox issues.

06:44:05   Downloading https://nexus3.opendaylight.org/repository/PyPi/packages/sphinx-bootstrap-theme/0.7.1/sphinx-bootstrap-theme-0.7.1.tar.gz (1.2 MB)
06:44:05 ERROR: Could not find a version that satisfies the requirement Sphinx~=3.2.0 (from lfdocs-conf->-r docs/requirements.txt (line 1)) (from versions: 0.1.61611, 0.1.61798, 0.1.61843, 0.1.61945, 0.1.61950, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.5, 0.5.1, 0.5.2b1, 0.5.2, 0.6b1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 1.0b1, 1.0b2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.2b1, 1.2b2, 1.2b3, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3b1, 1.3b2, 1.3b3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.4a1, 1.4b1, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5a1, 1.5a2, 1.5b1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6b1, 1.6b2, 1.6b3, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.7.0b1, 1.7.0b2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.8.0b1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5)
06:44:05 ERROR: No matching distribution found for Sphinx~=3.2.0 (from lfdocs-conf->-r docs/requirements.txt (line 1))
06:44:05 
06:44:05 =================================== log end ====================================
06:44:05 
ERROR: could not install deps [-rdocs/requirements.txt]; v = InvocationError(u'/w/workspace/builder-tox-verify-master/.tox/docs/bin/python -m pip install -rdocs/requirements.txt', 1)
06:44:05 jjb-version create: /w/workspace/builder-tox-verify-master/.tox/jjb-version

Patch-set: 1
Reviewer: Gerrit User 6258 <6258@7fc14799-209e-464c-9743-7a06c2c21a81>