Update patch set 2
Patch Set 2:

> I tried to push a job after pulling this review local and I got
 > this error:
 > 
 > jenkins_jobs.errors.JenkinsJobsException: openstack-cloud parameter
 > missing to format {openstack-cloud}

Fixed, missed a typo in  Iab772ed33f1d4e21617cb4169f6eb4818bb7866e and missing defaults in template in  I6b3abb6f2acfe1d5d68d2d802690ca6e433e20ba

Patch-set: 2