Update patch set 1
Patch Set 1:

Temporary comments:
Sandbox example of job run: https://jenkins.opendaylight.org/sandbox/job/bgpcep-csit-1node-cds-basicpcep-only-master/2/
*-all-master jobs are failing, and I think it is a genuine bug as ODL is returning 404 instead pcep-topology even 15 minutes after start. Those jobs may be still useful to keep track and gather karaf log.
To get jobs to Sandbox, I had to comment out lines mentioning findbugs (in bgpcep.yaml) to avoid this error:
  jenkins_jobs.errors.JenkinsJobsException: Unknown entry point or macro 'findbugs' for component type: 'reporter'.
No idea why, I have even upgraded to python-jenkins-0.4.5

Patch-set: 1