Update patch set 3
Patch Set 3:

(1 comment)

> I'd rather not rename every job in JJB

Do we have scripts for that yet? :)

Anyway, I have noticed that job rename only goes through if the job being renamed is not running (I am not sure what about if it is pending, waiting for slave). So such a global rename operation can be tricky to achieve on our active RelEng Jenkins.

> AttributeError: 'OrderedDict' object has no attribute 'iterkeys'

Really? Which version of Python are we running? Maybe iter() would work instead.

I was just following link from this line "See also: Equivalent OrderedDict recipe that runs on Python 2.4 or later." from:
https://docs.python.org/2/library/collections.html?highlight=ordereddict#collections.OrderedDict

Patch-set: 3