Update patch set 1
Patch Set 1: Code-Review-2

I tried to push a job after pulling this review local and I got
this error:

jenkins_jobs.errors.JenkinsJobsException: openstack-cloud parameter missing to format {openstack-cloud}

Patch-set: 1
Label: Code-Review=-2