Update patch set 4
Patch Set 4:

(5 comments)

> Build Failed
 > 
 > https://jenkins.opendaylight.org/releng/job/builder-jjb-verify/915/
 > : FAILURE
 > 
 > No problems were identified. If you know why this problem occurred,
 > please add a suitable Cause for it. ( https://jenkins.opendaylight.org/releng/job/builder-jjb-verify/915/
 > )
 > 
 > Logs: https://logs.opendaylight.org/releng/jenkins092/builder-jjb-verify/915
 > 
 > https://jenkins.opendaylight.org/releng/job/builder-verify-tox-master/1514/
 > : SUCCESS
 > 
 > Logs: https://logs.opendaylight.org/releng/jenkins092/builder-verify-tox-master/1514

stuck on these errors, guess we need to avoid using arrays:

    component_data, template_data, allow_empty_variables)
  File "/home/abelur/.virtualenvs/jjb/local/lib/python2.7/site-packages/jenkins_jobs/formatter.py", line 46, in deep_format
    raise JenkinsJobsException(desc)
jenkins_jobs.errors.JenkinsJobsException: bl_len parameter missing to format #!/bin/bash
# shellcheck disable=SC2034,SC2154
# Script to filter Jenkins jobs against a blacklist
# output: newline & comma-separated list

system="releng"
search_string="$SEARCH_STRING"

Patch-set: 4
Label: Verified=0