CI: Remove CentOS 7/8 cloud configs from Jenkins
Remove 20 cloud configuration files for CentOS 7 and CentOS Stream 8
Jenkins cloud nodes. Both CentOS 7 (EOL June 2024) and CentOS Stream 8
(EOL May 2024) OpenStack images have been deleted from VexxHost,
causing the jenkins-cfg-verify job to fail with:

ERROR: No matching image found for ZZCI - CentOS 7 - builder - x86_64
ERROR: No matching image found for ZZCI - CentOS Stream 8 - builder - x86_64

All ODL jobs have already been migrated to Ubuntu 22.04 or 24.04 nodes
and no JJB job definitions reference centos7 or centos8 build-node labels.

Removed configs (13 CentOS 7, 7 CentOS 8):

  CentOS 7: builder-{2c-1g,2c-2g,2c-8g,4c-4g,4c-16g,8c-8g},
            docker-{1c-4g,2c-2g,2c-8g,4c-4g},
            helm-{2c-2g,4c-4g}, robot-2c-8g
  CentOS 8: builder-{2c-1g,2c-2g,2c-8g,4c-4g,4c-16g,8c-8g},
            robot-2c-8g

This also unblocks the openstack-cron image-protect step which calls
'openstack image show' for each cloud config image and fails on
deleted images.

Change-Id: Ib8d54309a222a95bb68de513cdee619775dff609
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>