Update patch set 9
Patch Set 9:

> When I tried this to create integration-multipatch-test-carbon on
 > Sandbox, I got 500. Any idea on ho to log more details?
 > 
 > WARNING:root:logrotate is deprecated on jenkins>=1.637, use the
 > property build-discarder on newer jenkins instead
 > WARNING:jenkins_jobs.modules.publishers:trigger-parameterized-builds:Using
 > deprecated order for parameter sets in triggered-parameterized-builds.
 > This will be changed in a future release to inherit the order from
 > the user defined yaml. To enable this behaviour immediately, set
 > the config option '__future__.param_order_from_yaml' to 'true' and
 > change the input job configuration to use the desired order
 > INFO:jenkins_jobs.builder:Number of jobs generated:  1
 > INFO:jenkins_jobs.builder:Reconfiguring jenkins job
 > integration-multipatch-test-carbon
 > Traceback (most recent call last):
 > File "/home/vrpolak/.virtualenv/jjb/bin/jenkins-jobs", line 11, in
 > <module>
 > sys.exit(main())
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins_jobs/cmd.py",
 > line 191, in main
 > execute(options, config)
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins_jobs/cmd.py",
 > line 372, in execute
 > n_workers=options.n_workers)
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins_jobs/builder.py",
 > line 412, in update_jobs
 > parallelize=p_params)
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins_jobs/parallel.py",
 > line 112, in parallelized
 > return func(*args, **kwargs)
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins_jobs/builder.py",
 > line 435, in parallel_update_job
 > self.jenkins.update_job(job.name, job.output().decode('utf-8'))
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins_jobs/parallel.py",
 > line 112, in parallelized
 > return func(*args, **kwargs)
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins_jobs/builder.py",
 > line 161, in update_job
 > self.jenkins.reconfig_job(job_name, xml)
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins/__init__.py",
 > line 1019, in reconfig_job
 > DEFAULT_HEADERS))
 > File "/home/vrpolak/.virtualenv/jjb/local/lib/python2.7/site-packages/jenkins/__init__.py",
 > line 448, in jenkins_open
 > e.code, e.msg)
 > jenkins.JenkinsException: Error in request. Possibly authentication
 > failed [500]: Server Error

I have tested the patch which works. https://jenkins.opendaylight.org/sandbox/job/integration-multipatch-test-beryllium/

Thanh is correct, we can't a new job types pushed on Jenkins when there is an existing job type which is possibly different.

Patch-set: 9