Update patch set 3
Patch Set 3:

> > jenkins.BadHTTPException: Error communicating with
 > server[https://jenkins.opendaylight.org/releng/]
 > 
 > Ouch. Should we retry?

Yes communication related problems is usually because Jenkins is too busy.

Patch-set: 3