Update patch set 5
Patch Set 5:

> > > > AttributeError: 'OrderedDict' object has no attribute
 > > 'iterkeys'
 > > >
 > > > Really? Which version of Python are we running? Maybe iter()
 > > would
 > > > work instead.
 > >
 > > Strange, I tried running this again today after rebasing and it
 > > worked this time.
 > 
 > Strange, I'm getting this attribute error again today :(

Ok I think it's my local python install that's having issues. If I switch to my JJB virtualenv it works, but if I use my system level Python it fails.

Patch-set: 5