Update patch set 3
Patch Set 3:

> Build Failed
 > 
 > https://jenkins.opendaylight.org/releng/job/builder-jjb-verify/456/
 > : FAILURE
 > 
 > No problems were identified. If you know why this problem occurred,
 > please add a suitable Cause for it. ( https://jenkins.opendaylight.org/releng/job/builder-jjb-verify/456/
 > )
 > 
 > Logs: https://logs.opendaylight.org/releng/jenkins092/builder-jjb-verify/456
 > 
 > https://jenkins.opendaylight.org/releng/job/builder-verify-tox-master/1057/
 > : SUCCESS
 > 
 > Logs: https://logs.opendaylight.org/releng/jenkins092/builder-verify-tox-master/1057
Error: 

jenkins_jobs.errors.JenkinsJobsException: Unknown entry point or macro 'lf-infra-deploy-maven-file' for component type: 'builder'.
DEBUG:jenkins_jobs.builder:Cache written out to '/home/jenkins/.cache/jenkins_jobs/cache-host-jobs-https___jenkins_opendaylight_org_releng.yml'
Build step 'Execute shell' marked build as failure

I think the above tox failures are caused due to builder definition not being available i global-jjb.

Patch-set: 3
Label: Verified=0