Update patch set 10
Patch Set 10:

While other jobs can still be created on Sandbox, this patch set causes this:
jenkins.JenkinsException: Error in request. Possibly authentication failed [500]: Server Error

Patch-set: 10
Label: Verified=0