Fix integration-distribution-mri-test-phosphorus
ERROR: Build aborted. Can't trigger undefined projects. 1 of the below project(s) can't be resolved:
 > netconf-csit-1node-scale-max-devices-only-master

Caused by mismatch between netconf CSIT job definitions. There is
just no such thing as 'sulfur' nor 'stable/phosphorus'.

Change-Id: I24cec6b96e9faca05a3c8ea9ecbe27054f9ff716
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>