Use python3 in ansible builder, python2 is EOL
tox verify fails with
   ImportError: No module named zipp
because zipp no longer supports python2.x

Signed-off-by: Aric Gardner <agardner@linuxfoundation.org>
Change-Id: I66bc2582376932db446d12806b2f0d58c211a934