Update patch set 2
Patch Set 2:

I see the error in the verify job log:
  jenkins_jobs.errors.JenkinsJobsException: jre parameter missing to format {jre}

Patch-set: 2