Update patch set 1
Patch Set 1:

> ERROR:   jenkins-jobs: commands failed

I'm hitting the same issue while testing. What am I missing here?

Patch-set: 1