Update patch set 3
Patch Set 3:

> (1 comment)
 > > I'd rather not rename every job in JJB
 > Do we have scripts for that yet? :)

Not yet, I'll try to look into this soon.

 > Anyway, I have noticed that job rename only goes through if the job
 > being renamed is not running (I am not sure what about if it is
 > pending, waiting for slave). So such a global rename operation can
 > be tricky to achieve on our active RelEng Jenkins.

Thanks for letting me know. This will certainly be something we'll need to be aware of. Worst case we shutdown Jenkins over some weekend and rename all jobs at the shell level.

 > > AttributeError: 'OrderedDict' object has no attribute 'iterkeys'
 > Really? Which version of Python are we running? Maybe iter() would
 > work instead.
 
I tried with Python 3.4.3 and Python 2.7.10 and both got the same issue. I'll look at it more closely next chance I get to see if I can figure out what the issue is here. I'm guessing it ran for you?

Patch-set: 3